쿠폰 레포,서비스 추가  및 일간 리포트 구현
CoolPeace-yanolza/backend pull request #25
Opened 2024-01-03 09:58 UTC by KwonJuHwan

- 멘토링 이후, Batch를 멀티 모듈로 뺄 지 결정 후, Merge를 하겠습니다.
- close #18

2024-01-03 10:05 UTC, tkddn204 requested changes

2024-01-03 10:05 UTC, tkddn204 commented on src/main/java/com/coolpeace/domain/coupon/dto/response/CouponDailyResponse.java
> +}
🤔 DTO 컨벤션에 대해서 한번 논의를 해보면 좋을 것 같습니다. 저 같은 경우는 빌더를 사용하지 않고 아래처럼 메소드로 생성하는 방식을 사용했었어요.

https://github.com/CoolPeace-yanolza/backend/blob/28f9b6a6147f2e2daa337001a117039658a9e618/src/main/java/com/coolpeace/domain/member/dto/response/MemberLoginResponse.java#L5-L13)

2024-01-04 02:28 UTC, tkddn204 requested changes

2024-01-04 06:14 UTC, KwonJuHwan commented on src/main/java/com/coolpeace/domain/coupon/dto/response/CouponDailyResponse.java
> +}
메소드로 생성하는 방식으로 변경하였습니다

2024-01-04 06:16 UTC, tkddn204 approved these changes

2024-01-04 06:21 UTC, merged